modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="mario_craft"
version="1.0.0"
displayName="Mario Craft"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Virtu, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mario_craft]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mario_craft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration